name: captable
services:
  pg:
    image: postgres:15
    container_name: captable-database
    environment:
      - POSTGRES_USER=captable
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=captable
    ports:
      - 54321:5432
    volumes:
      - postgres_raw:/var/lib/postgresql/data  

  smtp:
    image: axllent/mailpit
    container_name: captable-smtp
    ports:
      - 8025:8025
      - 1025:1025
  minio:
    image: minio/minio
    container_name: captable-minio
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=captable
      - MINIO_ROOT_PASSWORD=password
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001" --address ":9002"'

  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #   container_name: captable-app
  #   command: ['run', 'dev']
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - "../.env.example"
  #     - "../.env"
  #   volumes:
  #     - ./:/opt/captable
  #     - node_modules:/opt/captable/node_modules
  #     - dist:/opt/captable/dist

  #   depends_on:
  #     - pg
  #     - smtp
  #     - minio

  # minio client - is expected to be run once to setup minio buckets. It'll exit 0 after setup
  mc:
    image: minio/mc
    container_name: captable-minio-client
    entrypoint: sh
    command: -c "
      mc alias set myminio http://minio:9002 captable password;
      mc mb myminio/captable-private-bucket;
      mc mb myminio/captable-public-bucket;
      mc policy set public myminio/captable-public-bucket;
      exit 0;
     "
    depends_on:
      - minio

volumes:
  minio:
  postgres_raw:
  node_modules:
  dist:
