name: opencap
services:
  database:
    image: postgres:15
    container_name: opencap-database
    environment:
      - POSTGRES_USER=opencap
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opencap
    ports:
      - 54321:5432
    volumes:
      - postgres_raw:/var/lib/postgresql/data  

  inbucket:
    image: inbucket/inbucket
    container_name: opencap-mailserver
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100
  
  minio:
    image: minio/minio
    container_name: opencap-minio
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=opencap
      - MINIO_ROOT_PASSWORD=password
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001" --address ":9002"'


  mc:
    image: minio/mc
    container_name: opencap-minio-client
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config;
      /usr/bin/mc config host add myminio http://minio:9002 opencap password;
      /usr/bin/mc mb myminio/opencap-private-bucket;
      /usr/bin/mc mb myminio/opencap-public-bucket;
      /usr/bin/mc anonymous set public myminio/opencap-public-bucket;
      exit 0;
      "
    depends_on:
      - minio

volumes:
  minio:
  postgres_raw:
