name: opencap
services:
  database:
    image: postgres:15
    container_name: opencap-database
    environment:
      - POSTGRES_USER=opencap
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opencap
    ports:
      - 54321:5432

  inbucket:
    image: inbucket/inbucket
    container_name: opencap-mailserver
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100
  
  minio:
  image: minio/minio
  container_name: opencap-minio
  ports:
    - 9002:9002
    - 9001:9001
  volumes:
    - minio:/data
  environment:
    MINIO_ROOT_USER: opencap
    MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" --address ":9002" /data

volumes:
  minio: