name: Fly Production Deploy
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  release:
    types: [published]

jobs:
  deploy:
    name: ğŸš€ Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸšš Move Dockerfile to root
        run: |
          mv ./docker/Dockerfile ./Dockerfile
      
      - name: ğŸª° Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: ğŸš€ Deploy Production
        run: flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
